### ISSUE TITLE
Python 3 compatibility roadmap

### ISSUE THREAD

**Issue by Zopieux** [Zopieux/ivre#1]
See [#upstream/10](/cea-sec/ivre/pull/10).

- [ ] 2to3 on full tree, to identify unconverted files
- [ ] Fix/review 2to3 changes
- [ ] Use six everywhere instead of random `try/except ImportError` in some places
- [ ] Remove references to str, unicode & cie ; use `six.string_types` instead
- [ ] Replace `type(foo) in (bar, baz)` ([O](https://stereochro.me/ideas/type-vs-isinstance) [M](http://docs.quantifiedcode.com/python-code-patterns/readability/do_not_compare_types_use_isinstance.html) [G](http://www.siafoo.net/article/56)) with `isinstance(foo, (bar, baz))`
